services:
  social-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: social-api:latest
    container_name: social-api
    restart: unless-stopped
    networks:
      - social-network
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./backend/pkg/db/migrations:/app/backend/pkg/db/migrations
    expose:
      - "8080"

  social-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: social-frontend:latest
    container_name: social-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
    networks:
      - social-network
    expose:
      - "3000"
    depends_on:
      - social-api

  social-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: social-nginx:latest
    container_name: social-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - social-network
    depends_on:
      - social-api
      - social-frontend

networks:
  social-network:
    driver: bridge
